site_name: RAS (rapid aligner seismic) documentation

nav:
    - Tutorials:
        - Run your own data: tutorials/tutorials.md
    - How-to Guides:
        - Installation: howto/installation.md
        - Examples: howto/examples.md
    - Reference: reference/reference.md
    - Discussions: discussions/discussions.md

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math

theme: readthedocs
